### ISSUE TITLE
Oomph setup does not install org.eclipse.emf.mwe2.launch

### ISSUE THREAD

**Issue by thSoft** [thSoft/elysium#138]
The Oomph setup fails:
```
Performing Launch /org.elysium/src/org/elysium/GenerateLilyPond.mwe2.launch
ERROR: org.eclipse.debug.core code=5020 Launch configuration type id "org.eclipse.emf.mwe2.launch.Mwe2LaunchConfigurationType" does not exist.
Possible causes:
	Missing specification of a launch type (missing plug-in)
	Incorrect launch configuration XML
  at org.eclipse.debug.internal.core.LaunchConfigurationInfo.initializeFromXML(LaunchConfigurationInfo.java:525)
  at org.eclipse.debug.internal.core.LaunchManager.createInfoFromXML(LaunchManager.java:955)
  at org.eclipse.debug.internal.core.LaunchManager.getInfo(LaunchManager.java:1371)
  at org.eclipse.debug.internal.core.LaunchConfiguration.getInfo(LaunchConfiguration.java:470)
  at org.eclipse.debug.internal.core.LaunchConfiguration.getAttribute(LaunchConfiguration.java:400)
  at org.eclipse.debug.internal.core.LaunchConfiguration.getModes(LaunchConfiguration.java:631)
  at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:758)
  at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
  at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:731)
  at org.eclipse.oomph.setup.launching.impl.LaunchTaskImpl.perform(LaunchTaskImpl.java:272)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3324)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:3267)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:4494)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:4488)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:4486)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3258)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3233)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3133)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:575)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:701)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```
In Installation Details > Installed Software, the following entry is present: `MWE2 Launcher	2.9.1.201705291011	org.eclipse.emf.mwe2.launcher.feature.group	Eclipse Xtext` But the plugin `org.eclipse.emf.mwe2.launch` is not installed. If I delete MWE2 Launcher from Installed Software, then rerun the P2 Director task, it gets installed properly.

**Comment by nittka** [comment]
A fresh installation works for me. My guess is that you already had a mwe2.launch installed which was only seemingly compatible (which is why Oomph did not update it).

**Comment by nittka** [comment]
A clean installation worked for me. My gess is that an mwe.launch was still present which seemed to be compatible but was in fact not.

**Comment by nittka** [comment]
I tried a clean installation today. Both with windows and linux, the launch plugin itself was not the problem (providing a lower bound for the plugin may help when updating the setup to a newer version, however).

Currently, executing the mwe launch within the setup process fails with a "workspace is closed" illegal state exception. I would deal with this issue in a separate ticket and close this one for now. Running the workflow manually after the installation works (and when working on the grammar you have to do that anyway), so this part of the setup does not have the highest priority.
